### ISSUE TITLE
fix License and Copyright

### ISSUE THREAD

**Issue by displague** [displague/csi-linode#1]
This repo is the product of many `sed` command search and replaces against documentation and cloud provider primitive object names.  There has also been some hand tweaking of API calls.

This repo is far from ready for public or private consumption.

The concern this issue seeks to address is that copyright and license notices were inadvertently modified along the way.  Figure out the correct solution and apply it.

https://opensource.stackexchange.com/a/5117
http://www.apache.org/dev/apply-license.html#copy-per-file
https://github.com/copper-engine/copper-engine/issues/33

Is the Copyright chain already broken? Does that matter? Reinstate potential holders?

- https://github.com/packethost/csi-packet/blob/master/LICENSE#L189
- https://github.com/packethost/csi-packet/blob/master/cmd/csi-packet-driver/main.go#L2
- https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/LICENSE#L189

- [x] Should be maintaining the [forked repo](https://github.com/digitalocean/csi-digitalocean/blob/master/LICENSE#L189)'s copyright.
- [x] The changelog needs some updating too as these updates are part of the license.
- [x] Should maintain original copyright from all files
     > https://www.apache.org/licenses/LICENSE-2.0 **4.c.**
     > You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and

---

I work at Linode, started this repo off hours from home, but pushed the committed/pushed repo at work.  In any case, IANAL and will seek the correct approach.

**Comment by cliedeman** [comment]
Can this be closed now?
